In [3]:
Introduction to NumPy: Vectors and Matrices

In [ ]:
Vectors and Matrices
Vectors
A vector has magnitude (size) and direction
Use NumPy to create a one-dimensional array
Vector can be created as row or column using NumPy

In [4]:
#Load NumPy Library 
import numpy as np 

In [5]:
#Create a vector as row 
vector_row = np.array([1, 2, 3])
print(vector_row) 

[1 2 3]


In [6]:
#Create a vector as column 
vector_column = np.array([[1], [2], [3]]) 
print(vector_column) 

[[1]
 [2]
 [3]]


In [ ]:
Matrix
In mathematics, a matrix is a rectangular array of numbers, symbols, or expressions, arranged in rows and columns
Rows tun horizontally and columns run vertically
Use NumPy to create a two-dimensional array

In [ ]:
Matrix Order
You can think of an  𝑟𝑥𝑐  matrix as a set of r row vectors, each having c elements; or you can think of it as a set of c column vectors, each having r elements.
The rank of a matrix is defined as (a) the maximum number of linearly independent column vectors in the matrix or (b) the maximum number of linearly independent row vectors in the matrix. Both definitions are equivalent.
If r is less than c, then the maximum rank of the matrix is r.
If r is greater than c, then the maximum rank of the matrix is c.

In [ ]:
Create a matrix using matrix()
Returns a matrix from an array type object ir string of data.
Syntax: np.matrix(data)


In [7]:
mat1 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")
print(mat1)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [ ]:
Create a using array()
Returns a matrix
Syntax: np.array(object)


In [8]:
mat2 = np.array([[1, 2], [3,4], [4, 6]])
print(mat2) 

[[1 2]
 [3 4]
 [4 6]]


In [ ]:
Matrix Properties
Shape
Returns number of rows and columns from a matrix
Syntax: mat.shape
shape[0] - returns the number of rows
shape[1] - returns the number of columns


In [9]:
mat3 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")

In [10]:
# shape 
mat3.shape

(3, 4)

In [11]:
# rows 
mat3.shape[0]

3

In [12]:
# columns 
mat3.shape[1]

4

In [ ]:
Size
Returns the number of elements from a matrix
Syntax: array.size

In [13]:
mat4 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")

In [14]:
# size 
mat4.size

12

In [ ]:
Modifying matrix using insert()
Adds values at a given position and axis in a matrix
Syntax: np.insert(matrix, object, values, axis)
matrix - input matrix
object - index position
values - matrix of values to be inserted

In [15]:
mat5 = np.matrix("1, 2, 3, 4; 4, 5, 6, 7; 7, 8, 9, 10")
print(mat5)

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [16]:
# adding a new matrix `col_new` as a new column to mat5
col_new = np.matrix("1, 1, 1")
print(col_new)

[[1 1 1]]


In [17]:
# insert at column 
mat6 = np.insert(mat5, 0, col_new, axis=1)
print(mat6) 

[[ 1  1  2  3  4]
 [ 1  4  5  6  7]
 [ 1  7  8  9 10]]


In [18]:
# adding a new matrix `row_new` as a new row to mat5
row_new = np.matrix("0, 0, 0, 0")
print(row_new)

[[0 0 0 0]]


In [19]:
# insert at row 
mat7 = np.insert(mat5, 0, row_new, axis=0)
print(mat7)

[[ 0  0  0  0]
 [ 1  2  3  4]
 [ 4  5  6  7]
 [ 7  8  9 10]]


In [ ]:
Modifying matrix using index
Elements of matrix can be modified using index number
Syntax:: mat[row_index, col_index)

In [20]:
mat_a = np.matrix("1, 2, 3, 4, 5; 5, 6, 7, 8, 9; 9, 10, 11, 12, 13")
print(mat_a)

[[ 1  2  3  4  5]
 [ 5  6  7  8  9]
 [ 9 10 11 12 13]]


In [23]:
# change 6 with 0 
mat_a[1, 1] = 0 

In [24]:
# show mat_a 
print(mat_a)

[[ 1  2  3  4  5]
 [ 5  0  7  8  9]
 [ 9 10 11 12 13]]


In [25]:
# extract 2nd row 
mat_a[1, :]

matrix([[5, 0, 7, 8, 9]])

In [26]:
# extract 3rd column
mat_a[:, 2]

matrix([[ 3],
        [ 7],
        [11]])

In [27]:
# extract elements 
mat_a[1, 2]

7

In [ ]:
Matrix Operations

In [28]:
A = np.arange(0, 20).reshape(5,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [29]:
B = np.arange(20, 40).reshape(5,4)
print(B)

[[20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]
 [32 33 34 35]
 [36 37 38 39]]


In [ ]:
Addition
np.add()- performs element-wise addition between two matrices
Syntax: np.add(matrix_1, matrix_2)

In [30]:
# addition 
np.add(A, B)

array([[20, 22, 24, 26],
       [28, 30, 32, 34],
       [36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

In [ ]:
Subtraction
np.subtract() - performs element-wise subtraction between two matrices.
Syntax: np.subtract(matrix_1, matrix_2)

In [31]:
# subtraction 
np.subtract(A,B)

array([[-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20],
       [-20, -20, -20, -20]])

In [ ]:
Transpose
np.transpose() - Permute the dimensions of an array.
Transposing an  𝑀×𝑁  matrix flips it around the center diagonal and results in an  𝑁×𝑀  matrix.
Syntax: np.transpose(matrix)

In [32]:
A = np.arange(0, 20).reshape(5,4)
print(A)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [35]:
# transpose 
np.transpose(A)

array([[ 0,  4,  8, 12, 16],
       [ 1,  5,  9, 13, 17],
       [ 2,  6, 10, 14, 18],
       [ 3,  7, 11, 15, 19]])

In [ ]:
Multiplication
np.dot() - performs matrix multiplication between two matrices.
Syntax: np.dot(matrix_1, matrix_2)

In [37]:
# multiplication
np.dot(A,B) 

ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

In [ ]:
Note

For matrix multiplication the number of columns in matrix  𝐴  should be equal to the number of rows in matrix  𝐵 
Here, Order of matrix  𝐴  =  5×4  and order of matrix  𝐵  =  5×4 
So,  5≠4 
That's why it shows ValueError: shapes (5,4) and (5,4) not aligned: 4 (dim 1) != 5 (dim 0)

In [38]:
# transpose matrix B to make it 4x5 in dimension
T = np.transpose(B)
print(T)

[[20 24 28 32 36]
 [21 25 29 33 37]
 [22 26 30 34 38]
 [23 27 31 35 39]]


In [39]:
# now we can perform multiplication
np.dot(A,T)

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [40]:
# using matmul 
np.matmul(A, T)

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [41]:
# using @ operator 
A @ T 

array([[ 134,  158,  182,  206,  230],
       [ 478,  566,  654,  742,  830],
       [ 822,  974, 1126, 1278, 1430],
       [1166, 1382, 1598, 1814, 2030],
       [1510, 1790, 2070, 2350, 2630]])

In [ ]:
Element-wise multiplication
np.multiply() - performs element-wise multiplication between two matrices.
Syntax: np.multiply(matrix1, matrix2)

In [42]:
# element-wise multiplication 
np.multiply(A, B)

array([[  0,  21,  44,  69],
       [ 96, 125, 156, 189],
       [224, 261, 300, 341],
       [384, 429, 476, 525],
       [576, 629, 684, 741]])

In [ ]:
Division
np.divide() - performs element-wise division between two matrices.
Syntax: np.divide(matrix_1, matrix_2)

In [43]:
# division
np.divide(A, B)

array([[0.        , 0.04761905, 0.09090909, 0.13043478],
       [0.16666667, 0.2       , 0.23076923, 0.25925926],
       [0.28571429, 0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471, 0.42857143],
       [0.44444444, 0.45945946, 0.47368421, 0.48717949]])

In [ ]:
References
[1]https://numpy.org/
[2]https://www.edureka.co/blog/python-numpy-tutorial/
[3]https://github.com/enthought/Numpy-Tutorial-SciPyConf-2019
[4]https://arm-software.github.io/CMSIS_5/DSP/html/group__groupMatrix.html